// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace GooglePlayGames
{
public static class GPGSIds
{
        public const string achievement_true_friend_ii = "CgkIi8ieyaIUEAIQDA"; // <GPGSID>
        public const string achievement_true_friend_i = "CgkIi8ieyaIUEAIQCw"; // <GPGSID>
        public const string achievement_hero = "CgkIi8ieyaIUEAIQEw"; // <GPGSID>
        public const string achievement_guru = "CgkIi8ieyaIUEAIQEg"; // <GPGSID>
        public const string achievement_gourmet_i = "CgkIi8ieyaIUEAIQDg"; // <GPGSID>
        public const string achievement_gourmet_ii = "CgkIi8ieyaIUEAIQDw"; // <GPGSID>
        public const string achievement_coach = "CgkIi8ieyaIUEAIQFQ"; // <GPGSID>
        public const string achievement_winner_i = "CgkIi8ieyaIUEAIQCA"; // <GPGSID>
        public const string achievement_great_8 = "CgkIi8ieyaIUEAIQGA"; // <GPGSID>
        public const string achievement_hard_worker_iii = "CgkIi8ieyaIUEAIQBw"; // <GPGSID>
        public const string achievement_hard_worker_i = "CgkIi8ieyaIUEAIQBA"; // <GPGSID>
        public const string achievement_honoured = "CgkIi8ieyaIUEAIQGQ"; // <GPGSID>
        public const string achievement_millionaire = "CgkIi8ieyaIUEAIQFw"; // <GPGSID>
        public const string achievement_collector_i = "CgkIi8ieyaIUEAIQAQ"; // <GPGSID>
        public const string achievement_hard_worker_ii = "CgkIi8ieyaIUEAIQBQ"; // <GPGSID>
        public const string achievement_gourmet_iii = "CgkIi8ieyaIUEAIQEA"; // <GPGSID>
        public const string achievement_chosen_one = "CgkIi8ieyaIUEAIQFg"; // <GPGSID>
        public const string achievement_collector_iii = "CgkIi8ieyaIUEAIQAw"; // <GPGSID>
        public const string achievement_true_friend_iii = "CgkIi8ieyaIUEAIQDQ"; // <GPGSID>
        public const string achievement_winner_ii = "CgkIi8ieyaIUEAIQCQ"; // <GPGSID>
        public const string achievement_collector_ii = "CgkIi8ieyaIUEAIQAg"; // <GPGSID>
        public const string achievement_winner_iii = "CgkIi8ieyaIUEAIQCg"; // <GPGSID>
        public const string achievement_moneybag = "CgkIi8ieyaIUEAIQEQ"; // <GPGSID>
        public const string achievement_patron = "CgkIi8ieyaIUEAIQGg"; // <GPGSID>
        public const string achievement_virtuoso = "CgkIi8ieyaIUEAIQFA"; // <GPGSID>

}
}
