// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace GooglePlayGames
{
public static class GPGSIds
{
        public const string achievement__iii = "CgkImtC8r_UKEAIQFA"; // <GPGSID>
        public const string achievement_ = "CgkImtC8r_UKEAIQGQ"; // <GPGSID>
        public const string achievement___i = "CgkImtC8r_UKEAIQDg"; // <GPGSID>
        public const string achievement__i = "CgkImtC8r_UKEAIQEg"; // <GPGSID>
        public const string achievement__ii = "CgkImtC8r_UKEAIQEw"; // <GPGSID>
        public const string achievement__8 = "CgkImtC8r_UKEAIQFw"; // <GPGSID>
        public const string achievement___iii = "CgkImtC8r_UKEAIQEA"; // <GPGSID>
        public const string achievement___ii = "CgkImtC8r_UKEAIQDw"; // <GPGSID>

}
}
